env:
  global:
  - DIST_REPO="dist"

script:
- scripts/build_dist.sh
- tar cvzf abc.tar.gz dist
- cp abc.tar.gz dist/
deploy:
  - provider: releases
    api_key:
      secure: AVWbis8wwDwwW3xHKgdtZvpQBMkZS3YxKsBajdwv4jtVO+Kb15kyMDuekN1I48gugWHQdwECYTqmdzsTdzS3V1yvnATSe9kTIA/ev6w6nQtoLNQ2kSYt/t9UH1CAL9rxD68HKyJ80rtacPY8KF33R7e6vwM85Wi7EC4rJFSDrslY5jTVOlPmM3jdpo/R68uP6p+68hQLz1lzu9WeMPQf8DVBnftxynN2B29gu+MskHYC78A+gcuvcYIGFSlvtG6K4G2Ys+35fQTNLgwMz1sAZcTO4J+UUkQRvB7RvKHtNRCZwduMmLslus4luGA7pN4FER+vzn5pnRLlcCo+CQeFxINtS4C+T9NqMyfaGBwG7KFGZEqU5vEiI0rEUH3NSfwhLm5bVXHXY9Fp2RMPb5yp1DBPv4e41Tf/BKzQzqd1+LetAmvS2MYWoyzPlUfIM+J3nQJWn7VzrEApAhe8nN1CpfK5VpAkoaP/WsfYifhactsu5DScKemwqcIM1xk5iM9wgP/YcGiZOTTbl3MIftAYE4kxKkWF5s+sQlt4TyGH2HGan6inpCu3Byux5txrEJVBIb2KZiDEUSOyNg/I94jJY/7y+A3e6wMZQ8W5NelsQksoGqdRL609v7B6x5V53cODXadowpjPlNFYxijmUQt6jTm0VeIzgjIsrymCJjo29CQ=
    file:
      - abc.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      repo: Niklaus-xie/f5-adcaas-openstack
      tags: true




